apiVersion: v1
kind: Pod
metadata:
  name: service-registry
  labels:
    app.kubernetes.io/name: service-registry
spec:
  containers:
  - name: service-registry
    image: perspective1974/serviceregistry:0.0.1
    ports:
      - containerPort: 8761
        name: sry
