apiVersion: v1
kind: Service
metadata:
  name: service-registry-svc
spec:
  selector:
    app.kubernetes.io/name: service-registry
  ports:
  - name: service-registry-svc
    protocol: TCP
    port: 80
    targetPort: 8761   